# Generated by Django 5.2.7 on 2025-10-30 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripadvisor_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('price_level', models.CharField(choices=[('free', 'Gratuit'), ('budget', '$'), ('moderate', '$$'), ('expensive', '$$$'), ('luxury', '$$$$')], default='budget', max_length=20)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('num_reviews', models.IntegerField(default=0)),
                ('num_photos', models.IntegerField(default=0)),
                ('num_likes', models.IntegerField(default=0)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('saves_count', models.IntegerField(default=0)),
                ('images', models.JSONField(blank=True, default=list)),
                ('awards', models.JSONField(blank=True, default=list)),
                ('attraction_groups', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-num_likes', '-rating'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('restaurant', 'Restaurant'), ('hotel', 'Hôtel'), ('monument', 'Monument'), ('museum', 'Musée'), ('park', 'Parc'), ('activity', 'Activité'), ('shopping', 'Shopping'), ('nightlife', 'Vie nocturne')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('capital', models.CharField(max_length=100)),
                ('capital_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('capital_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttractionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='gallery/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='tourism.attraction')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='attraction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourism.category'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='tourism.country'),
        ),
        migrations.CreateModel(
            name='UserAttractionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('visited', models.BooleanField(default=False)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.attraction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attraction_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('local', 'Local'), ('tourist', 'Touriste'), ('professional', 'Professionnel')], default='tourist', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourism.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttractionLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='tourism.attraction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'attraction')},
            },
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['country', 'city'], name='tourism_att_country_e7fd91_idx'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['category'], name='tourism_att_categor_1e52af_idx'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['-num_likes'], name='tourism_att_num_lik_267758_idx'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['price_level'], name='tourism_att_price_l_103dda_idx'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['ranking'], name='tourism_att_ranking_2ff500_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userattractionlist',
            unique_together={('user', 'attraction')},
        ),
    ]
